layout_spectrum: 0.4221508866176009
typography_spectrum: 0.549892412032932
color:
  brandStrength: 0.470231284853071
  lightness: 0.4000386567786336
  saturation: 0.5695541659370065
  rhythmicContrast: 0.08863018057309091
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
name: Millermore
